### ISSUE TITLE
Errors encountered when generating RISC-V RTL in WSL

### ISSUE THREAD

**Issue by huahdgithub** [eugene-tarassov/vivado-risc-v#187]
When generating RISC-V RTL in WSL Ubuntu terminal, I got the following error messages:
$ make CONFIG=rocket64b2 BOARD=nexys-a7-100t vivado-tcl
...
`java.nio.file.FileSystemException: /mnt/g/vivado-risc-v/target/streams/_global/dependencyPositions/_global/streams/update_cache_2.12/output_dsp: Operation not permitted`
`[error]         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)`
`[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)`
`[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)`
and so on.
Anybody can help?

**Comment by eugene-tarassov** [comment]
If /mnt/g is a Windows disk, it will not work. The tools require a Linux file system to run. Use the home directory in the WSL Ubuntu.

**Comment by huahdgithub** [comment]
> If /mnt/g is a Windows disk, it will not work. The tools require a Linux file system to run. Use the home directory in the WSL Ubuntu.
Thank you! And I also made some progress. WSL Ubuntu automatically mounts my portable HDD (where my G: partition lies). Before I first unmounted /mnt/g and then re-mounted it according to the instructions of this repo. Just now I omitted this umount-mount process and then the errors didn't show up.

**Comment by haipnh** [comment]
I can build this project on Ubuntu-20.04 on WSL2.
My command is `make CONFIG=rocket64b1 BOARD=arty-a7-100t bitstream`.
The bitstream can be written successfully.
